version: '2'
services:
  kalilinux:
    tty: true
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_kali
    cap_add:
      - NET_ADMIN
  metasploitable:
    tty: true
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_meta
    cap_add:
      - NET_ADMIN
    volumes:
      - ./volumes/meta:/etc
